version: '3.5'

services:

  social-local-shopping-demo:
    container_name: social-local-shopping-demo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
  mongo:
    image: mongo:4.0
    ports:
      - '27017:27017'
    volumes:
      - ./:/app:cached
